Add apache-commans-lang as a dependency
Needed after QPR3,
06-13 13:32:13.580 10174  4469  4520 E WM-WorkerWrapper: Work [ id=18b1ea72-9d9c-4fb2-bc8d-ef6d24fb887b, tags={ com.stevesoltys.seedvault.worker.AppBackupWorker,com.stevesoltys.seedvault.TAG_RESCHEDULE } ] failed because it threw an exception/error
06-13 13:32:13.580 10174  4469  4520 E WM-WorkerWrapper: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/lang3/time/DateUtils;

Change-Id: I4730648da69e97836a2373bc1883775a26e3e639